import { FluentProvider, webLightTheme } from '@fluentui/react-components';
import { MsalProvider } from '@azure/msal-react';
import { IntlProvider } from 'react-intl';
import { BrowserRouter, Link, Route, Routes } from 'react-router-dom';
import { msalInstance } from './auth/msalConfig';
import { AccessibilityMenu } from './components/AccessibilityMenu';
import { CookieBanner } from './components/CookieBanner';
import { LanguageSwitcher } from './components/LanguageSwitcher';
import { SkipNav } from './components/SkipNav';
import { SupportedLanguage } from './utils/language';
import { AccessibilityStatementPage } from './pages/AccessibilityStatementPage';
import { ApplyChildBenefitPage } from './pages/ApplyChildBenefitPage';
import { ApplyResidencyPage } from './pages/ApplyResidencyPage';
import { ApplyTaxCertPage } from './pages/ApplyTaxCertPage';
import { CaseDetailPage } from './pages/CaseDetailPage';
import { ConsentManagementPage } from './pages/ConsentManagementPage';
import { DemoScenarioPage } from './pages/DemoScenarioPage';
import { HomePage } from './pages/HomePage';
import { LoginPage } from './pages/LoginPage';
import { LogoutCallbackPage } from './pages/LogoutCallbackPage';
import { MyCasesPage } from './pages/MyCasesPage';
export function App({ locale, messages, onLocaleChange }: { locale: SupportedLanguage; messages: Record<string, string>; onLocaleChange: (l: SupportedLanguage) => void }) { return <MsalProvider instance={msalInstance}><IntlProvider locale={locale} messages={messages} defaultLocale="en"><FluentProvider theme={webLightTheme}><BrowserRouter><CookieBanner /><SkipNav /><header className="site-header"><Link to="/" className="brand"><span className="brand-logo" aria-hidden="true">UD</span><span>UDCSP<span style={{color:'var(--color-fg-soft)',fontWeight:500,marginLeft:'.4rem',fontSize:'.85rem'}}>Citizen Portal</span></span></Link><nav className="site-nav" aria-label="Main"><Link to="/cases">My cases</Link><Link to="/consent">Consent</Link><Link to="/accessibility">Accessibility</Link><Link to="/login">Sign in</Link></nav><div className="header-tools"><LanguageSwitcher value={locale} onChange={onLocaleChange} /></div></header><main id="main-content" tabIndex={-1}><Routes><Route path="/" element={<HomePage locale={locale} />} /><Route path="/apply/residency" element={<ApplyResidencyPage />} /><Route path="/apply/tax-certificate" element={<ApplyTaxCertPage />} /><Route path="/apply/child-benefit" element={<ApplyChildBenefitPage />} /><Route path="/cases" element={<MyCasesPage />} /><Route path="/cases/:id" element={<CaseDetailPage />} /><Route path="/accessibility" element={<><AccessibilityStatementPage /><AccessibilityMenu /></>} /><Route path="/consent" element={<ConsentManagementPage />} /><Route path="/login" element={<LoginPage />} /><Route path="/logout-callback" element={<LogoutCallbackPage />} /><Route path="/demo/:id" element={<DemoScenarioPage />} /></Routes></main><footer className="site-footer"><div className="site-footer__inner"><div className="site-footer__brand"><span className="brand-logo" aria-hidden="true">UD</span><span>Unified Digital Citizen Services Platform</span></div><nav aria-label="Footer"><Link to="/accessibility">Accessibility</Link><Link to="/consent">Consent &amp; privacy</Link><a href="https://github.com/fredgis/UDCSP" rel="noreferrer">About this platform</a></nav><div>© {new Date().getFullYear()} UDCSP · EU sovereign</div></div></footer></BrowserRouter></FluentProvider></IntlProvider></MsalProvider>; }
