<#
.SYNOPSIS
    Binds a procured PSTN number (E.164) to the country ACS resource and
    persists the binding in apps/voice/acs/phone-number-bindings.yaml so
    Install-Voice / Test-Voice can rediscover it.

.DESCRIPTION
    PSTN number procurement in ACS is a multi-step manual flow gated by a
    regulatory documentation pack (see docs/biz/voice.md § 9). Once the
    number has been issued, this script:

      1. Verifies the number is owned by the country ACS resource via
         `az communication phonenumber list`.
      2. Adds an entry to apps/voice/acs/phone-number-bindings.yaml with
         the orchestrator FQDN as the inbound webhook target.
      3. Optionally registers the same FQDN as the IncomingCall webhook on
         the country ACS resource (this is also done via Event Grid by
         Deploy-Voice; this step is a defence-in-depth confirmation).

.PARAMETER Country
    dk | se | no.

.PARAMETER Env
    dev | test | prod.

.PARAMETER PhoneNumber
    E.164 number procured (e.g. +4570701234).

.PARAMETER AcsResourceName
    Name of the existing country ACS resource.

.PARAMETER ResourceGroup
    Resource group of the ACS resource.

.PARAMETER OrchestratorFqdn
    FQDN of the deployed voice orchestrator Container App.

.PARAMETER NumberType
    tollFree | geographic.

.PARAMETER BindingsFile
    Path to phone-number-bindings.yaml (default: apps/voice/acs/phone-number-bindings.yaml).
#>
[CmdletBinding(SupportsShouldProcess)]
param(
    [Parameter(Mandatory)][ValidateSet('dk','se','no')][string]$Country,
    [Parameter(Mandatory)][ValidateSet('dev','test','prod')][string]$Env = 'dev',
    [Parameter(Mandatory)][string]$PhoneNumber,
    [Parameter(Mandatory)][string]$AcsResourceName,
    [Parameter(Mandatory)][string]$ResourceGroup,
    [Parameter(Mandatory)][string]$OrchestratorFqdn,
    [ValidateSet('tollFree','geographic')][string]$NumberType = 'tollFree',
    [string]$BindingsFile
)

$ErrorActionPreference = 'Stop'
$repoRoot = Resolve-Path (Join-Path $PSScriptRoot '..\..\..')
if (-not $BindingsFile) {
    $BindingsFile = Join-Path $repoRoot 'apps\voice\acs\phone-number-bindings.yaml'
}

if (-not (Get-Command az -ErrorAction SilentlyContinue)) {
    throw "Azure CLI ('az') is required on PATH."
}

# 1. Verify ownership.
Write-Host "▶ Verifying $PhoneNumber is owned by ACS resource '$AcsResourceName'…"
$listJson = az communication phonenumber list --resource-group $ResourceGroup --communication-service $AcsResourceName --output json 2>$null
if ($LASTEXITCODE -ne 0 -or -not $listJson) {
    Write-Warning "Unable to list phone numbers via az; skipping ownership verification (operator must confirm)."
} else {
    $owned = ($listJson | ConvertFrom-Json) | Where-Object { $_.phoneNumber -eq $PhoneNumber }
    if (-not $owned) {
        throw "PhoneNumber '$PhoneNumber' is not owned by ACS resource '$AcsResourceName'. Submit the regulatory pack first (docs/biz/voice.md § 9)."
    }
    Write-Host "  ✔ Number is owned by '$AcsResourceName'."
}

# 2. Persist the binding.
$bindingEntry = @"
  - country: $Country
    env: $Env
    phoneNumber: $PhoneNumber
    numberType: $NumberType
    acsResource: $AcsResourceName
    inboundWebhook: https://$OrchestratorFqdn/api/acs/eventgrid
    boundAt: $(Get-Date -Format 'yyyy-MM-ddTHH:mm:ssZ')
"@

if (-not (Test-Path $BindingsFile)) {
    if ($PSCmdlet.ShouldProcess($BindingsFile, "create with header + first binding")) {
        @"
# Generated by apps/voice/scripts/Bind-AcsNumber.ps1 — see docs/biz/voice.md §9.4
bindings:
$bindingEntry
"@ | Set-Content -Path $BindingsFile -Encoding UTF8
        Write-Host "  ✔ Created $BindingsFile with first binding."
    }
} else {
    $existing = Get-Content $BindingsFile -Raw
    if ($existing -match [regex]::Escape("phoneNumber: $PhoneNumber")) {
        Write-Host "  • Binding for $PhoneNumber already exists — leaving file untouched."
    } else {
        if ($PSCmdlet.ShouldProcess($BindingsFile, "append binding for $PhoneNumber")) {
            Add-Content -Path $BindingsFile -Value $bindingEntry -Encoding UTF8
            Write-Host "  ✔ Appended binding for $PhoneNumber."
        }
    }
}

Write-Host "✔ Bind-AcsNumber finished for $PhoneNumber → $OrchestratorFqdn"
